name: busmap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Thêm package để hỗ trợ đổi icon

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bus.png"  # Đường dẫn icon phải chính xác

flutter:
  uses-material-design: true
  assets:
    - assets/images/
